import { buildAllPdfReport, buildPersonPdfReport } from './pdf-report';
import { entry, person } from '../test/fixtures/golden';

const NOW = new Date('2026-08-09T12:00:00.000Z');

describe('PDF reports', () => {
  it('builds a person report with Georgian text, totals, and escaped notes', () => {
    const report = buildPersonPdfReport(
      person({
        id: 'giorgi',
        name: 'გიორგი',
        entries: [entry({ comment: '<script>alert(1)</script>' })],
      }),
      'personal',
      NOW,
    );
    expect(report.filename).toContain('acc-person');
    expect(report.html).toContain('გიორგი');
    expect(report.html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
    expect(report.html).not.toContain('<script>alert(1)</script>');
    expect(report.html).toContain('Generated by ACC');
  });

  it('builds one complete report for Personal and Work data', () => {
    const report = buildAllPdfReport(
      {
        personal: [person({ id: 'p', name: 'Personal record' })],
        work: [person({ id: 'w', name: 'Work team' })],
      },
      NOW,
    );
    expect(report.filename).toBe('acc-complete-report-2026-08-09.pdf');
    expect(report.html).toContain('Personal record');
    expect(report.html).toContain('Work team');
    expect(report.html).toContain('Complete report');
  });
});
