import { buildAllPdfReport, buildPersonPdfReport, openPdfPrintDialog } from './pdf-report';
import { entry, person } from '../test/fixtures/golden';

const NOW = new Date('2026-08-09T12:00:00.000Z');

describe('PDF reports', () => {
  it('builds a person report with Georgian text, totals, and escaped notes', () => {
    const report = buildPersonPdfReport(
      person({
        id: 'giorgi',
        name: 'გიორგი',
        entries: [entry({ comment: '<script>alert(1)</script>' })],
      }),
      'personal',
      NOW,
    );
    expect(report.filename).toContain('acc-person');
    expect(report.html).toContain('გიორგი');
    expect(report.html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
    expect(report.html).not.toContain('<script>alert(1)</script>');
    expect(report.html).toContain('Generated by ACC');
  });

  it('builds one complete report for Personal and Work data', () => {
    const report = buildAllPdfReport(
      {
        personal: [person({ id: 'p', name: 'Personal record' })],
        work: [person({ id: 'w', name: 'Work team' })],
      },
      NOW,
    );
    expect(report.filename).toBe('acc-complete-report-2026-08-09.pdf');
    expect(report.html).toContain('Personal record');
    expect(report.html).toContain('Work team');
    expect(report.html).toContain('Complete report');
  });

  it('prints only the generated report from the main document on Android-compatible print', () => {
    vi.useFakeTimers();
    const print = vi.spyOn(window, 'print').mockImplementation(() => undefined);
    const focus = vi.spyOn(window, 'focus').mockImplementation(() => undefined);
    openPdfPrintDialog(
      buildPersonPdfReport(person({ id: 'p', name: 'Printable person' }), 'personal', NOW),
    );

    const printRoot = document.querySelector('.acc-print-root');
    expect(printRoot).toHaveTextContent('Printable person');
    expect(document.querySelector('iframe')).not.toBeInTheDocument();
    expect(document.querySelector('style[media="print"]')).toHaveTextContent(
      'body > *:not(.acc-print-root)',
    );

    vi.advanceTimersByTime(50);
    expect(print).toHaveBeenCalledOnce();
    window.dispatchEvent(new Event('afterprint'));
    expect(document.querySelector('.acc-print-root')).not.toBeInTheDocument();
    print.mockRestore();
    focus.mockRestore();
    vi.useRealTimers();
  });
});
